# Generated by Django 4.1.2 on 2022-11-11 15:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_resized.forms


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('addressLine1', models.TextField(blank=True, max_length=200, null=True)),
                ('addressLine2', models.TextField(blank=True, max_length=200, null=True)),
                ('city', models.TextField(blank=True, max_length=200, null=True)),
                ('state', models.TextField(blank=True, max_length=200, null=True)),
                ('country', models.TextField(blank=True, max_length=200, null=True)),
                ('postalCode', models.TextField(blank=True, max_length=200, null=True)),
                ('profile_image', django_resized.forms.ResizedImageField(crop=None, force_format=None, keep_meta=True, quality=90, scale=None, size=[200, 200], upload_to='profile_image')),
                ('uniqueId', models.CharField(blank=True, max_length=100, null=True)),
                ('slug', models.SlugField(blank=True, max_length=500, null=True, unique=True)),
                ('date_created', models.DateTimeField(blank=True, null=True)),
                ('last_updated', models.DateTimeField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
